export enum DRIVER_STATUS_ENUM {
  OFFLINE = 'OFFLINE',
  FREE = 'FREE',
  DELIVERY = 'DELIVERY',
}

export const ACCEPTANCE_RATE_MAX = 100;

export const EXPIRE_CACHE_DRIVER = 60 * 60 * 14; // 14 h

export const DRIVER_FUNCTION_CALLING = {
  DRIVER_UPDATE_LOCATION: 'DRIVER_UPDATE_LOCATION',
  DRIVER_UPDATE_STATUS: 'DRIVER_UPDATE_STATUS',
  DRIVER_UPDATE_INFO: 'DRIVER_UPDATE_INFO',
  DRIVER_UPDATE_AVATAR: 'DRIVER_UPDATE_AVATAR',
};
