export const NOTE_MAX_LENGTH = 255;

export enum ORDER_STATUS_ENUM {
  PENDING = 'PENDING',
  PENDING_PICKUP = 'PENDING_PICKUP',
  PICKED_UP = 'PICKED_UP',
  SUCCESS = 'SUCCESS',
  CANCEL = 'CANCEL',
  RELEASE = 'RELEASE',
}
