export const NOTE_MAX_LENGTH = 255;

export enum ORDER_STATUS_ENUM {
  PENDING = 'PENDING',
  PENDING_PICKUP = 'PENDING_PICKUP',
  PICKED_UP = 'PICKED_UP',
  SUCCESS = 'SUCCESS',
  RETURN = 'RETURN',
  RETURNING = 'RETURNING',
  RETURNED = 'RETURNED',
  CANCELED = 'CANCELED',
  RELEASE = 'RELEASE',
}

export enum ORDER_ASSIGNMENT_STATUS_ENUM {
  ASSIGNED = 'ASSIGNED',
  REJECTED = 'REJECTED',
  EXPIRE = 'EXPIRE',
}

export const MAX_DISTANCE = 3000; // 3 km
export const IS_PENDING_ORDER_KEY = 'is_pending_order';
export const EXPIRE_CACHE_PENDING_ORDER = 60 * 60 * 24; // 1 day
