export enum SPECIAL_REQUIRE_ENUM {
  EXTRA_CAPACITY_W_EQUIPMENT = 'EXTRA_CAPACITY_W_EQUIPMENT', // Extra capacity with equipment (Baga)
  EXTRA_CAPACITY_W = 'EXTRA_CAPACITY_W', // Extra capacity without equipment
  ROUND_TRIP = 'ROUND_TRIP',
  DOOR_TO_DOOR_DRIVER = 'DOOR_TO_DOOR_DRIVER',
  DOOR_TO_DOOR_DRIVER_HELPER = 'DOOR_TO_DOOR_DRIVER_HELPER',
  THERMAL_BAG = 'THERMAL_BAG',
}
