openapi: 3.0.0
paths:
  /api/mail:
    post:
      operationId: MailController_sendMail
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - Mail
  /api/admin/me:
    get:
      operationId: AdminController_meProfile
      parameters: []
      responses:
        '200':
          description: Successful get admin profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMeDTO'
      summary: Get admin profile
      tags:
        - Admin
  /api/driver-manage/driver:
    post:
      operationId: DriverManageController_createDriver
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDriverInput'
      responses:
        '200':
          description: Driver created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseDTO'
                  - properties:
                      data:
                        type: boolean
                        example: true
      summary: Create a driver
      tags: &ref_0
        - driver-manage
    get:
      operationId: DriverManageController_getAllDriver
      parameters: []
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseDTO'
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/CreateDriverInput'
      summary: Get all driver
      tags: *ref_0
  /api/driver-manage/driver/info:
    post:
      operationId: DriverManageController_createInfo
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDriverInfoInput'
      responses:
        '201':
          description: Partner created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCreateDriverInfoDTO'
      summary: Create a partner identification info
      tags: *ref_0
    put:
      operationId: DriverManageController_updateInfo
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDriverInfoInput'
      responses:
        '200':
          description: Update partner identification info
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseDTO'
                  - properties:
                      data:
                        type: boolean
                        example: true
      summary: Create a partner identification info
      tags: *ref_0
  /api/transport-type:
    get:
      operationId: TransportTypeController_find
      parameters: []
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseDTO'
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/TransportTypeDTO'
      summary: Get all transport types
      tags:
        - transport-type
  /api/auth-admin/login:
    post:
      operationId: AuthAdminController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminLoginInput'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseDto'
        '400':
          description: Bad request
      summary: Admin user login
      tags:
        - auth-admin
  /api/driver-auth/register:
    post:
      operationId: DriverAuthController_register
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDriverInput'
      responses:
        '201':
          description: Register Partner
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseDTO'
                  - properties:
                      data:
                        type: boolean
                        example: true
      summary: Register Partner
      tags: &ref_1
        - Driver Auth
  /api/driver-auth/login:
    post:
      operationId: DriverAuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DriverLoginInput'
      responses:
        '200':
          description: Refresh Login success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseDTO'
                  - properties:
                      data:
                        type: object
                        $ref: '#/components/schemas/ClientLoginResponseDto'
        '401':
          description: Unauthorized
      summary: Driver login
      tags: *ref_1
  /api/driver-auth/refresh-token:
    post:
      operationId: DriverAuthController_refreshToken
      parameters: []
      responses:
        '200':
          description: Refresh token for driver
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseDTO'
                  - properties:
                      data:
                        type: object
                        $ref: '#/components/schemas/ClientLoginResponseDto'
      summary: Refresh token for driver
      tags: *ref_1
  /api/image/signed-url:
    post:
      operationId: ImageController_signedUrl
      parameters: []
      responses:
        '200':
          description: Return signed URL
          content:
            application/json:
              schema:
                type: string
      summary: Get signed URL
      tags:
        - image
  /api/user-auth/login:
    post:
      operationId: UserAuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerLoginInput'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSession'
        '401':
          description: Unauthorized
      summary: Customer login
      tags: &ref_2
        - user-auth
  /api/user-auth/refresh-token:
    get:
      operationId: UserAuthController_refreshToken
      parameters: []
      responses:
        '200':
          description: Successful refresh token
        '401':
          description: Unauthorized
      summary: Refresh token
      tags: *ref_2
info:
  title: Shipppee system API
  description: The Shipppee system API description
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    Data:
      type: object
      properties:
        name:
          type: string
          description: Admin name
          example: Nguyen Cong Gioi
        username:
          type: string
          description: Admin username
          example: admin
        id:
          type: number
          description: Admin user ID
          example: '12'
      required:
        - id
    ResponseMeDTO:
      type: object
      properties:
        code:
          type: number
          example: 200
          description: status code
        success:
          type: boolean
          example: true
          description: status
        message:
          type: string
          example: success
          description: message
        timestamp:
          type: string
          example: '2021-09-01T14:00:00.000Z'
          description: timestamp
        data:
          description: Data
          allOf:
            - $ref: '#/components/schemas/Data'
      required:
        - code
        - success
        - message
        - timestamp
        - data
    CreateDriverInput:
      type: object
      properties:
        name:
          type: string
          description: Driver name
          example: Cong Gioi
        email:
          type: string
          description: Driver email
          example: conggioi.pro264@gmail.com
        password:
          type: string
          description: Driver password
          example: '123456'
        phone:
          type: string
          description: Driver phone number
          example: '0123456789'
        transportTypeId:
          type: number
          description: Transport type ID
          example: '1'
      required:
        - name
        - email
        - password
        - phone
        - transportTypeId
    CreateDriverInfoInput:
      type: object
      properties:
        idDriver:
          type: number
          description: Driver ID
          example: 1
        province:
          type: string
          description: Province
          example: Quang Ngai
        district:
          type: string
          description: District
          example: Binh Son
        ward:
          type: string
          description: Ward
          example: Binh Hai
        identityCardNumber:
          type: string
          description: Identity card number
          example: '123456789'
        licensePlates:
          type: string
          description: license plates
          example: 76C193934
        images:
          description: List of images
          example: '[]'
          type: array
          items:
            type: string
      required:
        - idDriver
        - province
        - district
        - ward
    ResponseCreateDriverInfoDTO:
      type: object
      properties:
        code:
          type: number
          example: 200
          description: status code
        success:
          type: boolean
          example: true
          description: status
        message:
          type: string
          example: success
          description: message
        timestamp:
          type: string
          example: '2021-09-01T14:00:00.000Z'
          description: timestamp
        data:
          example:
            id: 1
            idDriver: 1
            province: Quang Ngai
            district: Binh Son
            ward: Binh Hai
          description: Data
          allOf:
            - $ref: '#/components/schemas/CreateDriverInfoInput'
      required:
        - code
        - success
        - message
        - timestamp
        - data
    UpdateDriverInfoInput:
      type: object
      properties:
        idDriver:
          type: number
          description: Driver ID
          example: 1
        province:
          type: string
          description: Province
          example: Quang Ngai
        district:
          type: string
          description: District
          example: Binh Son
        ward:
          type: string
          description: Ward
          example: Binh Hai
        identityCardNumber:
          type: string
          description: Identity card number
          example: '123456789'
        licensePlates:
          type: string
          description: license plates
          example: 76C193934
        images:
          description: List of images
          example: '[]'
          type: array
          items:
            type: string
    AdminLoginInput:
      type: object
      properties:
        username:
          type: string
          description: Admin username
          example: admin
        password:
          type: string
          description: Admin password
          example: '123456'
      required:
        - username
        - password
    LoginResponseDto:
      type: object
      properties:
        code:
          type: number
          example: 200
          description: status code
        success:
          type: boolean
          example: true
          description: status
        message:
          type: string
          example: success
          description: message
        timestamp:
          type: string
          example: '2021-09-01T14:00:00.000Z'
          description: timestamp
        data:
          description: Response data
          example:
            token: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFkbWluIiwiaWF0IjoxNTE2MjM5MDIyfQ.4S5s2
          allOf:
            - $ref: '#/components/schemas/Data'
      required:
        - code
        - success
        - message
        - timestamp
        - data
    DriverLoginInput:
      type: object
      properties:
        password:
          type: string
          description: Driver password
          example: '123456'
        phone:
          type: string
          description: Driver phone number
          example: '0123456789'
      required:
        - password
        - phone
    CustomerLoginInput:
      type: object
      properties:
        email:
          type: string
          example: conggioi@gmail.com
        password:
          type: string
          example: '********'
      required:
        - email
        - password
    UserSession:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - CUSTOMER
            - DRIVER
            - ADMIN
            - SUPER_ADMIN
        phone:
          type: string
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - id
        - name
        - email
        - role
        - phone
        - accessToken
        - refreshToken
    ResponseDTO:
      type: object
      properties:
        code:
          type: number
          example: 200
          description: status code
        success:
          type: boolean
          example: true
          description: status
        message:
          type: string
          example: success
          description: message
        timestamp:
          type: string
          example: '2021-09-01T14:00:00.000Z'
          description: timestamp
      required:
        - code
        - success
        - message
        - timestamp
    ClientLoginResponseDto:
      type: object
      properties:
        accessToken:
          type: string
          description: Access token
          example: ''
        refreshToken:
          type: string
          description: Refresh token
          example: ''
        expiresIn:
          type: number
          description: Token expiration time
          example: ''
      required:
        - accessToken
        - refreshToken
        - expiresIn
    TransportTypeDTO:
      type: object
      properties:
        id:
          type: string
          description: Transport type ID
          example: '1'
        name:
          type: string
          description: Transport name
          example: Xe máy
        imageUrl:
          type: string
          description: Transport type image URL
          example: https://media-shipppee.nguyenconggioi.me/moto_bike.png
        description:
          type: string
          description: Transport type description
          example: Hoạt động tất cả khung giờ, chở tối đa 100kg
        code:
          type: string
          enum:
            - BIKE
            - VAN_500
            - VAN_1T
            - TRUCK_1T
            - TRUCK_1T5
            - TRUCK_2T
          description: Transport type code
          example: BIKE
        loadWeight:
          type: number
          description: Transport type load weight
          example: 100000
        textWeight:
          type: string
          description: Transport type text weight
          example: 100Kg
        textSize:
          type: string
          description: Transport type text size
          example: 1 x 1 x 1 m
      required:
        - id
        - name
        - imageUrl
        - description
        - code
        - loadWeight
        - textWeight
        - textSize
