name: Deploy Development to Heroku

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Test and Lint
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
